name: CI
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/syself/caph-builder:1.0.27
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fix git safe.directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Download modules
        run: go mod download

      - name: Verify go.mod and go.sum are tidy
        run: |
          go mod tidy
          git diff --exit-code -- go.mod go.sum

      - name: Verify generated README
        run: |
          go generate ./...
          git diff --exit-code -- README.md

      - name: Verify formatting
        run: test -z "$(gofmt -l .)"

      - name: Run tests
        run: go test ./...

      - name: Build
        run: go build ./...
